// ⚠️ PLACEHOLDER FILE — DO NOT USE AS-IS ⚠️
//
// This file is normally auto-generated by running:
//   flutterfire configure
// after creating a Firebase project and adding your Android app to it.
// That command overwrites this file with your project's real API keys,
// app IDs, etc. See README.md → "Firebase setup" for the exact steps.
//
// Leaving this placeholder in place will fail at runtime with a clear
// "default FirebaseOptions have not been configured" error, which is
// intentional — it's a reminder, not a silent failure.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform. '
          'Run `flutterfire configure` — see README.md.',
        );
    }
  }

  // Replace these via `flutterfire configure` — do not hand-edit.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDDcpYam019LtoOg9QazPf86nUSbvQhlA',
    appId: '1:837128956056:android:09cab8d42164123724c8ed',
    messagingSenderId: '837128956056',
    projectId: 'oil-spill-alert-app',
    storageBucket: 'oil-spill-alert-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME',
    iosBundleId: 'REPLACE_ME',
  );
}
