import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'models/alert.dart';
import 'services/notification_service.dart';
import 'screens/home_screen.dart';

// Generated by `flutterfire configure` — see README for setup steps.
import 'firebase_options.dart';

final GlobalKey<HomeScreenState> homeScreenKey = GlobalKey<HomeScreenState>();

// MVP flag: set to true once you've run `flutterfire configure` with real
// Firebase keys and want push notifications working. Keep false to run the
// app immediately with just the UI + mock alerts (no Firebase needed at all).
const bool kEnablePushNotifications = true;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  if (kEnablePushNotifications) {
    await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  }
  runApp(const OilSpillAlertApp());
}

class OilSpillAlertApp extends StatefulWidget {
  const OilSpillAlertApp({super.key});

  @override
  State<OilSpillAlertApp> createState() => _OilSpillAlertAppState();
}

class _OilSpillAlertAppState extends State<OilSpillAlertApp> {
  @override
  void initState() {
    super.initState();
    if (kEnablePushNotifications) {
      NotificationService.init(
        onAlertReceived: (OilSpillAlert alert) {
          homeScreenKey.currentState?.addAlertToTop(alert);
        },
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Oil Spill Alerts',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorSchemeSeed: const Color(0xFF0B5D8C), // ocean blue
        useMaterial3: true,
        appBarTheme: const AppBarTheme(centerTitle: false),
      ),
      home: HomeScreen(key: homeScreenKey),
    );
  }
}